FROM ubuntu:17.10
MAINTAINER Stefan Köhnen

RUN apt-get update && apt-get install curl wget vim python-pip less python-pysaml2 libssl-dev iputils-ping git && pip install -U pip setuptools && pip install -U python-openstackclient lxml oauthlib python-swiftclient
